apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backstage-system

namePrefix: backstage-

resources:
- ../../../crd
- ../../../rbac
- ../../../manager
- namespace.yaml

images:
- name: controller
  newName: quay.io/rhdh-community/operator
  newTag: 0.7.0

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - default-config/app-config.yaml
  - default-config/db-secret.yaml
  - default-config/db-service.yaml
  - default-config/db-statefulset.yaml
  - default-config/deployment.yaml
  - default-config/service.yaml
  name: default-config
