apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  labels:
    app: rhdh-operator
    app.kubernetes.io/part-of: rhdh
spec:
  selector:
    matchLabels:
      app: rhdh-operator
  template:
    metadata:
      labels:
        app: rhdh-operator
        app.kubernetes.io/component: rhdh-operator
    spec:
      containers:
        - name: manager
          env:
            - name: OPERATOR_NAME
              value: rhdh-operator
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RELATED_IMAGE_postgresql
              value: quay.io/fedora/postgresql-15:latest
            - name: RELATED_IMAGE_backstage
              value: quay.io/rhdh-community/rhdh:next
            - name: RELATED_IMAGE_catalog_index
              value: quay.io/rhdh/plugin-catalog-index:1.9
          # flavor volume mounts
          volumeMounts:
              - mountPath: /default-config/flavors/orchestrator
                name: flavor-orchestrator
              - mountPath: /default-config/flavors/ai
                name: flavor-ai
        # flavor volumes
      volumes:
        - name: flavor-orchestrator
          configMap:
            name: flavor-orchestrator
            optional: true
        - name: flavor-ai
          configMap:
            name: flavor-ai
            optional: true
