apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: metrics-rbac
    app.kubernetes.io/created-by: rhdh-operator
    app.kubernetes.io/instance: metrics-reader
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: rhdh-operator
  name: rhdh-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
