## Append samples you want in your CSV to this file as resources ##
resources:
- _v1alpha5_backstage.yaml
- _v1alpha4_backstage.yaml
- _v1alpha3_backstage.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
